---
title: "try1"
author: "Andrea Zermeño Díaz"
date: "`r Sys.Date()`"
output: html_document
---
Example with a co-exclusion and co-occurrence to evaluate the performance of the code

```{r}
library(tidyverse)


station <- c("site_1", "site_2", "site_3", "site_4", "site_5", "site_6", 
             "site_7", "site_8", "site_9", "site_10")
bgc_1 <- c(1, 2, 1, 0, 1, 0, 0, 0, 0, 1)
bgc_2 <- c(1, 0, 1, 0, 0, 0, 1, 1, 0, 0) # co-occurrence
bgc_3 <- c(2, 0, 0, 0, 0, 0, 1, 1, NA, 1) # co-exclusion

bgcs_by_sites <- data.frame(station, bgc_1, bgc_2, bgc_3)

mag_1 <- c(2, 0, 1, 0, 0, 0, 3, 1, 0, 0) # co-occurrence 
mag_2 <- c(1, 3, 0, 0, 0, 1, 0, 0, 0, 1)
mag_3 <- c(0, 1, 1, 0, 0, 2, NA, 0, 1, 1) # co-exclusion

mags_by_sites <- data.frame(station, mag_1, mag_2, mag_3)

```


```{r}
# tablas donde se van a guardar informacion de los patrones
co_occur <- data.frame(mags = character(), bgcs = character(), total_sites = integer(), 
                       stringsAsFactors = FALSE)

co_exclu <- data.frame(mags = character(), bgcs = character(), total_sites = integer(), 
                       mag_sites= integer(), bgc_sites = integer(), stringsAsFactors = FALSE)

for (col1 in colnames(motus_by_sites)) {
  if (col1 == "station") next  # Ignoramos la columna station
  
  for (col2 in colnames(gcfs_by_sites)) {
    if (col2 == "station") next  # Ignoramos la columna station

    # select the station column and the current column for both tables
    temp1 <- motus_by_sites[, c("station", col1), drop = FALSE]
    temp2 <- gcfs_by_sites[, c("station", col2), drop = FALSE]
    
    # bind by col1 and col2 by station, because some bgcs aren't in all the stations, 
    # because not all mags have bgcs, so if we do a inner join we will loose information (a possible (1,0)
    # relevant for us)
    temp3 <- full_join(temp1, temp2, by = "station")
    
    # convertir a 0 los NAs generados por el join
    temp3[[col1]] <- ifelse(is.na(temp3[[col1]]), 0, temp3[[col1]]) 
    temp3[[col2]] <- ifelse(is.na(temp3[[col2]]), 0, temp3[[col2]])
    
    # eliminar sitios en donde no hay ningun mag ni bgc presente (dobles ceros)
    temp3 <- temp3[!(temp3[[col1]] == 0 & temp3[[col2]] == 0), ]
    if (nrow(temp3) == 0) next 
    
    # co-ocurrencia
    if (all((temp3[[col1]] > 0) == (temp3[[col2]] > 0))) { # co-ocurrencia
      
      co_occur <- rbind(co_occur, data.frame(mags= col1, bgcs= col2, total_sites= nrow(temp3)))
      
    }
    # co-exclusion
    if (all((temp3[[col1]] == 0 & temp3[[col2]] > 0) | (temp3[[col1]] > 0 & temp3[[col2]] == 0))) { 
      
      mags_sum <- sum(temp3[[col1]] > 0) # cuantos mags estan en los sitios
      bgcs_sum <- sum(temp3[[col2]] > 0) # vs. cuantos bgcs estan en los sitios
      
      co_exclu <- rbind(co_exclu, data.frame(mags= col1, bgcs= col2, total_sites= nrow(temp3), 
                                             mag_sites = mags_sum, bgc_sites = bgcs_sum ))
    }
  }
}



print(co_occur)
print(co_exclu)



```
-----------------------------------------------------------------------

##### Probabilities #########

Obtaining the probability (pi) for each case of co-exclusion/co-occurrence for a binomial test. Observe how it acts with the ratio between MAGs and BGCs.

```{r}
# Ejemplo aleatorio de como se veria el dataset
Dat <- tibble(
  total = 256,
  coex = rpois(n = 100, lambda = 15), 
  mags = sample(letters[1:4], size = 100, replace = TRUE),
  bgcs = sample(LETTERS[1:4], size = 100, replace = TRUE)) %>%
  rowwise() %>%
  mutate(
    mag_sites = sample(0:coex, 1),
    bgc_sites = coex - mag_sites) %>%
  ungroup()


Dat_stats<- Dat %>%
  mutate(
    p = bgc_sites/total, #P(bgc)
    q = mag_sites/total, #P(mag)
    pi  = ((p) * (1 - (q))) + ((q) * (1 - (p))) # P(mag=1,bgc=0) + P(mag=0, bgc=1)
  )                                             # = p - (2*p*q) + q

ggplot(Dat_stats, aes(x = p, y = q, fill = pi)) +
  geom_tile() +                  
  scale_fill_viridis_c() +      
  labs(x = "p", y = "q", fill = "pi") +
  theme_minimal()
#------------------------------------------------------------------
# Mejor simulamos para diferentes combinacion de probabilidades de p y q

p <- seq(0.01, 1, length.out = 100) 
q <- seq(0.01, 1, length.out = 100)

Dat2 <- expand.grid(p = p, q = q) %>% # combinaciones
  as_tibble() %>%
  mutate(
    pi_e = ((p) * (1 - (q))) + ((q) * (1-(p))), # = p - (2*p*q) + q
    pi_o = p * q
  )

ggplot(Dat2, aes(x = p, y = q, fill = pi_e)) +
  geom_tile() +                  
  scale_fill_viridis_c() +      
  labs(x = "p", y = "q", fill = "pi") +
  theme_minimal()

ggplot(Dat2, aes(x = p, y = q, fill = pi_o)) +
  geom_tile() +                  
  scale_fill_viridis_c() +      
  labs(x = "p", y = "q", fill = "pi") +
  theme_minimal()
```
El radio ente mags y bgcs: la probabilidad pi de que esten en co-exclusion magi y bgcj es menos probable cuando la prbabilidad de que el magi y de que el bgcj este en n sitios sea la misma.Tambien es mas probablie que pase si hay un desbalance.

Porbabilidad de co-ocurrencia: la porbabilidad pi de que esten en co_ocurrencia magi y bgcj es mas baja cuando la probabilidad de que ambos esten presentes sea baja, lo mismo si hay un desbalance. 
-------------------------------------------------------------------------

##### Binomial test ######






